name: Team CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install  # run after install
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: test  # run after test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linters
        run: |
          pip install flake8 pylint

      - name: Run Flake8
        run: flake8 . --count --max-complexity=10 --max-line-length=88 --statistics

      - name: Run Pylint
        run: pylint **/*.py || true  # Let workflow continue even if pylint fails

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: lint  # run after lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build Project
        run: |
          echo "Simulating build step — package or zip your app here"
